appconfig/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('medical.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

medical/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from medical import views

urlpatterns = [
    path("", views.login, name="login"),
    path("cad/", views.cad, name="cadastro"),
    # path('login/', views.login, name='login')
    path("logout/", views.logout, name="logout"),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(),
        name="password_reset"
    ),
    path(
        "password_reset_done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<slug:uidb64>/<slug:token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),

    path('main/', views.main, name='main'),
    path('show_finalization_patient/', views.show_finalization_patient, name='show_finalization_patient'),

    # crud procedure secretaria
    path('show_procedure/', views.find_all_procedure, name='show_procedure'),
    path('create_procedure/', views.create_procedure, name='procedure'),
    path('update_procedure/<int:id>', views.update_procedure, name='update_procedure'),
    path("delete_procedure/<int:id>", views.delete_procedure, name="delete_procedure"),

    # crud recommendation secretaria
    path('show_recommendation/', views.find_all_recommendation, name='show_recommendation'),
    path('create_recommendation/', views.create_recommendation, name='reco'),
    path('update_recommendation/<int:id>', views.update_recommendation, name='update_recommendation'),
    path("delete_recommendation/<int:id>", views.delete_recommendation, name="delete_recommendation"),

    # crud patient
    path('show_patient/', views.find_all_patient, name='show_patient'),
    # path("create_patient/", views.create_patient, name="create_patient"),
    path('update_patient/<int:id>', views.update_patient, name='update_patient'), 
    path("delete_patient/<int:id>", views.delete_patient, name="delete_patient"),
    path("config_proc/<int:id>", views.config_proc, name="config_proc"),
    path("patient_config/<int:id>", views.patient_config, name="patient_config"),
    

    path("resetPassword/", views.resetPassword, name="resetPassword"),

    path("patient/", views.patient, name="patient"),
    path("calendar/", views.calendar, name="calendar"),

]   

medical/models.py
from django.contrib.auth.models import AbstractUser, User
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.hashers import make_password
from datetime import datetime, timedelta


class Recommendation(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)  
    phone = models.CharField(max_length=20,  null=True, blank=True)
    email = models.CharField(max_length=100,  null=True, blank=True)
    street = models.CharField(max_length=100,  null=True, blank=True)
    number = models.CharField(max_length=50,  null=True, blank=True)

    def __str__(self):
        return str(self.name)


class Users(AbstractUser):
    Association = (('Particular', 'particular'), ('Convênio', 'convenio'),)
    UF = (
        ('RO', 'Rondônia'),
        ('AC', 'Acre'),
        ('AM', 'Amazonas'),
        ('RR', 'Roraima'),
        ('PA', 'Pará'),
        ('AP', 'Amapá'),
        ('TO', 'Tocantins'),
        ('MA', 'Maranhão'),
        ('PI', 'Piauí'),
        ('CE', 'Ceará'),
        ('RN', 'Rio Grande do Norte'),
        ('PB', 'Paraíba'),
        ('PE', 'Pernambuco'),
        ('AL', 'Alagoas'),
        ('SE', 'Sergipe'),
        ('BA', 'Bahia'),
        ('MG', 'Minas Gerais'),
        ('ES', 'Espírito Santo'),
        ('RJ', 'Rio de Janeiro'),
        ('SP', 'São Paulo'),
        ('PR', 'Paraná'),
        ('SC', 'Santa Catarina'),
        ('RS', 'Rio Grande do Sul'),
        ('MS', 'Mato Grosso do Sul'),
        ('MT', 'Mato Grosso'),
        ('GO', 'Goiás'),
        ('DF', 'Distrito Federal'),
    )
    email = models.EmailField(unique=True)
    cpf = models.CharField('CPF', max_length=50, null=True)
    # avatar = models.ImageField(
    #     upload_to='medical/avatars/%Y/%m/%d/')
    birth_date = models.DateField('Data de Nascimento', null=True)
    street = models.CharField('Rua', max_length=100, null=True)
    number = models.CharField('Numero', max_length=50, null=True)
    district = models.CharField('Bairro', max_length=100, null=True)
    uf = models.CharField('UF', choices=UF, max_length=2, null=True)
    phone = models.CharField('Celular', max_length=20, null=True)
    procedure = models.ManyToManyField(
        'Procedure', through='UserProcedure', blank=True)
    created_at = models.DateField(auto_now_add=True, null=True)
    association = models.CharField(
        'Associação', choices=Association, max_length=20, null=True)
    bariatric = models.DateField(null=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def save(self, *args, **kwargs):
        if not self.pk and not self.password:
            self.password = make_password('opera')
        super().save(*args, **kwargs)

    def __str__(self):
        return str(self.username)


class Procedure(models.Model):

    title = models.CharField('Nome do procedimento',
                             max_length=255, null=False)
    description = models.TextField('Descrição', null=False)
    days_limit = models.IntegerField('Limite de dias', null=False)

    recommendation = models.ManyToManyField(
        Recommendation, blank=True, through='ProcedureReco')
    created_at = models.DateField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.title)


class ProcedureReco(models.Model):
    procedure = models.ForeignKey(Procedure, on_delete=models.CASCADE)
    recommendation = models.ForeignKey(
        Recommendation, on_delete=models.CASCADE)


class UserProcedure(models.Model):

    user = models.ForeignKey(Users, on_delete=models.CASCADE, related_name="procedures")
    procedure = models.ForeignKey(Procedure, on_delete=models.CASCADE)
    done = models.BooleanField('Feito', default=False)
    date_limit = models.DateField(null=True, blank=True)
    date_done = models.DateField(null=True, blank=True)
    type_procedure = models.BooleanField(null=True)


    # def save(self, *args, **kwargs):
    #     if not self.date_limit:
    #         self.date_limit = self.procedure.date_limit
    #     super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.user.username} - {self.procedure.title}'

medical/forms.py
from django import forms
from django.contrib.auth import forms
from django.forms import ChoiceField, Form, MultipleChoiceField

from .models import Procedure, Recommendation, Users


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = Users


class UserCreationForm(forms.UserCreationForm):
    class Meta(forms.UserCreationForm.Meta):
        model = Users

medical/views.py
from django.contrib import auth, messages
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.contrib.messages import constants
from django.shortcuts import HttpResponse, get_object_or_404, redirect, render
from django.db.models.signals import post_save
from django.dispatch import receiver
from medical.forms2 import formcadProc, formSug, formUser,FormUserProcedure
from medical.models import Procedure, Recommendation, Users, UserProcedure, ProcedureReco
from django.utils import timezone
import datetime
from django.db.models.signals import pre_save
from django.dispatch import receiver
from datetime import date
from datetime import datetime, timedelta


# from django.http import HttpResponse
def cad(request):
    if request.method == "GET":
        return render(request, "medical/pages/cad.html")
    elif request.method == "POST":
        username = request.POST.get("username")
        email = request.POST.get("email")
        senha = request.POST.get("senha")

        try:
            user = Users.objects.create_user(
                username=username, email=email, password=senha
            )
            user.save()
            return render(request, "medical/pages/home.html")
        except:
            return render(request, "medical/pages/cad.html")


def login(request):
    if request.method == "GET":
        return render(request, "medical/pages/login.html")
    elif request.method == "POST":
        username = request.POST.get("username")
        senha = request.POST.get("senha")

        user = auth.authenticate(username=username, password=senha)

        if not user:
            messages.add_message(
                request, constants.ERROR, "Username ou senha inválidos"
            )
            return redirect("/")
        else:
            auth.login(request, user)
            return redirect("/main")

def logout(request):
    auth.logout(request)
    return redirect("/")

@login_required(login_url='/')
def main(request):
    user = Users.objects.filter(is_superuser=False)
    today = date.today()
    
    usuarios_atrasados = UserProcedure.objects.filter(date_limit__lt = today)
    atrasos = []
    for users in usuarios_atrasados:
        if users.user not in atrasos:
            atrasos.append(users.user)
    # print(atrasos)
    
    usuarios_aptos = UserProcedure.objects.all()
    aptos = []
    for users1 in usuarios_aptos:

        if users1.done == True:
            if users1.user not in aptos:
                aptos.append(users1.user)
        else: 
            if users1.user in aptos:
                aptos.remove(users1.user)
    print(aptos)

    usuarios_atualizados = UserProcedure.objects.filter(done=True).order_by('-id')
    atualizados = []
    for users2 in usuarios_atualizados:
        if users2.user not in atualizados:
            atualizados.append(users2.user)
    # print(atualizados)
    # usuarios_atrasados = Users.objects.filter(userprocedure__date_limit__lt=today)
    # pacientes_aptos = Users.objects.exclude(userprocedure__isnull=True).exclude(userprocedure__done=False)
    # pacientes_atualizados = Users.objects.filter(userprocedure__done=True).order_by('-userprocedure__date_done')
    # qnt_aptos = Users.objects.exclude(userprocedure__isnull=True).exclude(userprocedure__done=False).count()
    # qnt_atrasados = Users.objects.filter(userprocedure__date_limit__lt=today).count()
    # qnt_atualizados = Users.objects.filter(userprocedure__done=True).order_by('-userprocedure__date_done').count()
    # {'qnt_atualizados':qnt_atualizados,'qnt_atrasados':qnt_atrasados,'qnt_aptos':qnt_aptos,'user':user,'usuarios_atrasados':usuarios_atrasados, 'pacientes_aptos':pacientes_aptos,'pacientes_atualizados':pacientes_atualizados}

    
    return render(request, 'medical/pages/main.html', {'user':user,'atrasos':atrasos,'atualizados':atualizados,'aptos':aptos,
                                                       'atualizadosc':len(atualizados),
                                                       'atrasosc':len(atrasos),
                                                       'aptosc':len(aptos),
                                                       })

from django.db.models.signals import post_save
from django.dispatch import receiver
from .models import UserProcedure

@receiver(post_save, sender=UserProcedure)
def update_date_limit(sender, instance, **kwargs):
    user_procedure = instance

    if user_procedure.done and user_procedure.date_limit is not None:
        user_procedure.date_limit = None
        user_procedure.save(update_fields=['date_limit'])

@login_required(login_url='/')
def show_finalization_patient(request):
    user = Users.objects.filter(is_superuser=False)
    qtnduser = Users.objects.filter(is_superuser = False).count()
    return render(request, 'medical/pages/show_finalization_patient.html',{'user':user})

# def cadrec(request):
#     pat = Users.objects.filter(is_superuser=False)
#     return render(request, 'medical/pages/cadrec.html', {'pat': pat})


# crud proc
@login_required(login_url='/')
def find_all_procedure(request):

    user = Users.objects.filter(is_superuser=False)
    procreco = ProcedureReco.objects.all()
    proc = Procedure.objects.filter()
    search = request.GET.get('search')
    if search:
        proc = proc.filter(title__icontains=search)
    paginator = Paginator(proc, 10)
    page = request.GET.get('page')
    proc = paginator.get_page(page)

    return render(request, 'medical/pages/show_procedure.html', {'proc': proc, 'user': user, 'procreco': procreco})


@login_required(login_url='/')
def create_procedure(request):
    form = formcadProc(request.POST)
    if request.method == 'POST':
        print(form.errors)
        if form.is_valid():
            form.save()
            return redirect('show_procedure')
    else:
        form = formcadProc()
    return render(request, 'medical/pages/procedure.html', {'formproc': form})


@receiver(post_save, sender=UserProcedure)
def atualizar_data(sender, instance, **kwargs):
    if instance.done:
        new_date = timezone.now()
        UserProcedure.objects.filter(pk=instance.pk).update(date_done=new_date)

@login_required(login_url='/')
def update_procedure(request, id):
    proc = Procedure.objects.get(id=id)
    form = formcadProc(instance=proc)

    if request.method == 'POST':
        form = formcadProc(request.POST, instance=proc)
        if form.is_valid():
            form.save()
            return redirect('show_procedure')
    return render(request, 'medical/pages/update_procedure.html', {'formproc': form})

@login_required(login_url='/')
def delete_procedure(request, id):
    proc = get_object_or_404(Procedure, pk=id)
    proc.delete()
    return redirect("show_procedure")


# crud recommedation
@login_required(login_url='/')
def find_all_recommendation(request):
    reco = Recommendation.objects.all()
    search = request.GET.get('search')
    if search:
        reco = reco.filter(name__icontains=search)
    
    paginator = Paginator(reco,10)
    page = request.GET.get('page')
    reco = paginator.get_page(page)
    return render(request, 'medical/pages/show_recommendation.html', {'reco': reco})

@login_required(login_url='/')
def create_recommendation(request):
    form = formSug(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('show_recommendation')
    return render(request, 'medical/pages/recommendation.html', {'formreco': form})

@login_required(login_url='/')
def update_recommendation(request, id):
    reco = Recommendation.objects.get(id=id)
    form = formSug(instance=reco)

    if request.method == 'POST':
        form = formSug(request.POST, instance=reco)
        if form.is_valid():
            form.save()
            return redirect('show_recommendation')
    return render(request, 'medical/pages/update_recommendation.html', {'formreco': form})

@login_required(login_url='/')
def delete_recommendation(request, id):
    reco = get_object_or_404(Recommendation, pk=id)
    reco.delete()
    return redirect("show_recommendation")

    # for user in users:
    #     print(f"Paciente: {user.username}")

    #     procedimentos_pre = user.userprocedure_set.filter(type_procedure='pre_op')
    #     for pre_op in procedimentos_pre:
    #         print(f"Procedimento pré-operatório: {pre_op.procedure.title}")

    #     procedimentos_pos = user.userprocedure_set.filter(type_procedure='pos_op')
    #     for pos_op in procedimentos_pos:
    #         print(f"Procedimento pós-operatório: {pos_op.procedure.title}")
    # user_id_to_filter = 94
    
    # user = users.filter(id=user_id_to_filter).first()
    # if user:
    #     print(f"User: {user.username}")
    #     pre_op_procedures = user.procedures.filter(type_procedure=True)
    #     for procedure in pre_op_procedures:
    #         print(f"  Pre-op Procedure: {procedure.procedure.title}")

@login_required(login_url='/')
def find_all_patient(request):
    users = Users.objects.filter(is_superuser=False).order_by('-id')
    userprocedure = UserProcedure.objects.all()

    search = request.GET.get('search')
    if search:
        users = users.filter(username__icontains=search)

    paginator = Paginator(users, 10)
    page = request.GET.get('page')
    users_page = paginator.get_page(page)

    return render(request, "medical/pages/show_patient.html", {
        'users': users_page,
        'userprocedure': userprocedure,
    })

# @login_required(login_url='/')
# def create_patient(request):
#     proc = Procedure.objects.all()
#     if request.method == "POST":
#         form = formUser(request.POST, request.FILES)
#         if form.is_valid():
#             instance = form.save(commit=False)
#             instance.password = make_password(instance.password)
#             instance.user = request.user

medical/templates/medical/pages/cad.html
{% extends 'medical/base.html' %}
{%load static%}
{% block header %}

{%endblock header %}
{%block css%}<link rel="stylesheet" href="../../static/medical/css/geral.css">{%endblock css%}
{% block body%}

<div class="opera">
  <img src="{% static 'medical/img/logo.png'%}" alt="Logo">
</div>
<br>
<br>
    <div class="container1">
        <form action="{%url 'cadastro'%}" method="POST">{% csrf_token %}
          <center><h4>Cadastrar Paciente</h4></center>
            <br>
            <label>Nome</label>
            <br>
            <input placeholder="Digite seu Username" type="text" name="username" class="form-control">
            <br>
            <label>Email</label>
            <br>
            <input placeholder="Digite seu Email" type="email" name="email" class="form-control">
            <br>
            <label>Senha</label>
            <input placeholder="Digite sua senha" type="password" name="senha" class="form-control">
            <br>
            <button type="submit" class="btn btn-dark medio">Cadastrar Usuário</button>
        </form>
    </div>
{%endblock body%}

medical/templates/medical/pages/calendar.html
<!-- linkagem de arquivos de estilização -->
{% extends 'medical/base.html' %} {%load static%} {% load crispy_forms_tags %}
{% block header%} {%endblock header%} {%block css%}
<link rel="stylesheet" href="../../static/medical/css/show_patient.css" />
<link rel="stylesheet" href="../../static/medical/css/basebar.css" />
<link rel="stylesheet" href="../../static/medical/css/component/loading.css" />
<link rel="stylesheet" href="../../static/medical/css/component/scrollBar.css" />
<link rel="stylesheet" href="../../static/medical/css/calendar.css" />
{%endblock css%} {% block body %} 
{%include 'medical/basebar.html'%}

<div class="container">
  {% include 'medical/pages/component/loading.html' %}

    <div class="left">
      <div class="calendar">
        <div class="month">
          <i class="fas fa-angle-left prev"></i>
          <div class="date">december 2015</div>
          <i class="fas fa-angle-right next"></i>
        </div>
        <div class="weekdays">
          <div>Sun</div>
          <div>Mon</div>
          <div>Tue</div>
          <div>Wed</div>
          <div>Thu</div>
          <div>Fri</div>
          <div>Sat</div>
        </div>
        <div class="days"></div>
        <div class="goto-today">
          <div class="goto">
            <input type="text" placeholder="mm/yyyy" class="date-input" />
            <button class="goto-btn">Go</button>
          </div>
          <button class="today-btn">Today</button>
        </div>
      </div>
    </div>
    <div class="right">
      <div class="today-date">
        <div class="event-day">wed</div>
        <div class="event-date">12th december 2022</div>
      </div>
      <div class="events"></div>
      <div class="add-event-wrapper">
        <div class="add-event-header">
          <div class="title">Add Event</div>
          <i class="fas fa-times close"></i>
        </div>
        <div class="add-event-body">
          <div class="add-event-input">
            <input type="text" placeholder="Event Name" class="event-name" />
          </div>
          <div class="add-event-input">
            <input
              type="text"
              placeholder="Event Time From"
              class="event-time-from"
            />
          </div>
          <div class="add-event-input">
            <input
              type="text"
              placeholder="Event Time To"
              class="event-time-to"
            />
          </div>
        </div>
        <div class="add-event-footer">
          <button class="add-event-btn">Add Event</button>
        </div>
      </div>
    </div>
    <button class="add-event">
      <i class="fas fa-plus"></i>
    </button>
  </div>

{%endblock body%}

medical/templates/medical/pages/config_proc.html
{% extends 'medical/base.html' %} {%load static%} {% load crispy_forms_tags %}
{% block header%} {%endblock header%} {%block css%}
<link rel="stylesheet" href="../../static/medical/css/basebar.css" />
<link rel="stylesheet" href="../../static/medical/css/component/scrollBar.css" />
<link rel="stylesheet" href="../../static/medical/css/config_proc.css" />
<link rel="stylesheet" href="../../static/medical/css/component/loading.css" />
{%endblock css%} {% block body %} {%include 'medical/basebar.html'%}

<div class="container">
{% include 'medical/pages/component/loading.html' %}

    <div class="title">
    <h2 class="listra-title">Configuração de procedimento</h2>
</div>
<div class="dates">
    <form>
        <div class="card-table">
            <table class="table">
                <thead>
                    <tr>
                    <th scope="col">Nome</th>
                    <th scope="col">Procedimento</th>
                    <th scope="col">Data Limite</th>
                    <th scope="col">Tipo</th>
                    <th scope="col">Editar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for userproc in userproc %}
                        <a href="{% url 'patient_config' userproc.id %}">
                            <tr>
                            <td>{{ userproc.user.username }}</td>
                            <td>{{ userproc.procedure.title }}</td>
                            <td>{{ userproc.date_limit}}</td>
                            <td>{% if userproc.type_procedure == False %}Pos {% else %}Pre{% endif %}</td>
                            <td><a href="{% url 'patient_config' userproc.id %}"><img class="pencil" title="Editar" src="../../static/medical/icon/pencil-solid.svg"></a></td>
                            </tr>
                        </a>
                        {% endfor %}
                </tbody>
            </table>
        </div>
    </form>
</div>

    
</div>
{% endblock body %}

medical/templates/medical/pages/create_patient.html
{% extends 'medical/base.html' %} {%load static%} {% load crispy_forms_tags %}

{% block header%} {%endblock header%} {%block css%}
<link rel="stylesheet" href="../../static/medical/css/update_patient.css" />
<link rel="stylesheet" href="../../static/medical/css/basebar.css" />
<link rel="stylesheet" href="../../static/medical/css/component/scrollBar.css"/>
{%endblock css%} {% block body%} {%include 'medical/basebar.html'%}
<div class="container">
  {% include 'medical/pages/component/loading.html' %}

  <div class="title">
    <h2 class="listra-title">Cadastrar Paciente</h2>
  </div>

  <div class="form-create_patient">
    <form action="#" method="POST" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="div-flex">
        <div class="inputs">
          <div class="name-input">{{formuser.username|as_crispy_field}}</div>
          <div class="email-input">{{formuser.email|as_crispy_field}}</div>
          <div class="phone-input">{{formuser.phone|as_crispy_field}}</div>
        </div>

        <div class="inputs">
          <div class="number-input">{{formuser.number|as_crispy_field}}</div>
          <div class="CPF-input">{{formuser.cpf|as_crispy_field}}</div>
          <div class="data-input">{{formuser.birth_date|as_crispy_field}}</div>
        </div>

        <div class="inputs">
          <div class="street-input">{{formuser.street|as_crispy_field}}</div>
          <div class="district-input">{{formuser.district|as_crispy_field}}</div>
          <div class="association-input">{{formuser.association|as_crispy_field}}</div>
          <div class="uf-input">{{formuser.uf|as_crispy_field}}</div>
        </div>
      </div>

      <div class="procedure-field">
        <div class="procedure-check">
          <label>aa</label>
          {{formuser.procedure|as_crispy_field }}
        </div>

        <div>
            <img class="image" src="../../static/medical/img/bro.png" >
        </div>
      </div>
    <div class="btn">
        <input type="submit" class="btn-create" value="Salvar" />
    </div>
    </form>
  </div>

</div>
{%endblock body%}

medical/templates/medical/pages/procedure.html
{% extends 'medical/base.html' %} {%load static%} {% load crispy_forms_tags %}
{% block header%} {%endblock header%} {%block css%}
<link rel="stylesheet" href="../../static/medical/css/basebar.css" />
<link rel="stylesheet" href="../../static/medical/css/procedure.css" />
<link rel="stylesheet" href="../../static/medical/css/component/scrollbar.css"/>
<link rel="stylesheet" href="../../static/medical/css/component/loading.css" />
{%endblock css%} {% block body %} {%include 'medical/basebar.html'%}

<div class="container">
    {% include 'medical/pages/component/loading.html' %}
  <div class="title">
    <h2 class="listra-title">Cadastrar Procedimento</h2>
  </div>
  <div>
    <form action="{%url 'procedure'%}" method="post">
      {% csrf_token %}
      <div>
        <div class="title-input">
            {{formproc.title|as_crispy_field}}
        </div>
        <div class="days-limit-input">
          {{formproc.days_limit|as_crispy_field}}
        </div>
      </div>
      <div class="description-input">
        {{formproc.description|as_crispy_field}}
      </div>
      <div class="recommendation-input">
        {{formproc.recommendation|as_crispy_field}}
      </div>
      <input class="btn-create_patient" type="submit" value="salvar" />
    </form>
  </div>
</div>
{% endblock body %}

medical/templates/medical/pages/show_procedure.html
{% extends 'medical/base.html' %} {%load static%} {% load crispy_forms_tags %}
{% block header%} {%endblock header%} {%block css%}
<link rel="stylesheet" href="../../static/medical/css/basebar.css" />
<link rel="stylesheet" href="../../static/medical/css/show_procedure.css"/>
<link rel="stylesheet" href="../../static/medical/css/component/search.css" />
<link rel="stylesheet" href="../../static/medical/css/component/scrollBar.css" />
<link rel="stylesheet" href="../../static/medical/css/component/modalDelete.css" />
<link rel="stylesheet" href="../../static/medical/css/component/loading.css" />
{%endblock css%} {% block body %} {%include 'medical/basebar.html'%}


<div class="container">
  {% include 'medical/pages/component/loading.html' %}
    <div class="title">
      <h2 class="listra-title">Procedimentos</h2>
    </div>
    {% include 'medical/pages/component/search.html' %}
    <div >
        <a href="{%url 'procedure'%}"><button class='btn-create' title="Cadastrar um exame">Cadastrar</button></a>
    </div>
    <div class="background-table">
        <table class="table table-light">
          <thead class="thead-light">
            <tr>
              <th scope="col" style="padding: 15px">Exame</th>
              <th scope="col" style="padding: 15px; padding-left: 125px">Data de cadastro</th>
              <th scope="col" style="padding: 15px">opções</th>
            </tr>
          </thead>
          <tbody>
            {% for proc in proc %}
            <tr data-toggle="collapse" data-target="#{{proc.id}}" class="accordion-toggle">
              <td class="listra" style="padding: 15px;">{{proc.title}}</td>
              <td style="padding: 15px; padding-left: 125px">{{u.created_at | date:"d/m/Y"}}</td>
              <td style="padding: 15px;"><a href="{% url 'update_procedure' proc.id %}"><img class="pencil" title="Editar" src="../../static/medical/icon/pencil-solid.svg"></a>
                <a data-bs-toggle="modal" data-bs-target="#exampleModal{{ proc.id }}"  style="margin-left:10px;"><img class="trash" title="excluir" src="../../static/medical/icon/trash-solid.svg"></a></td>
                
                <!-- Modal -->
                {% include 'medical/pages/component/modalDeleteProc.html' with mensagem='Gostaria de deletar este procedimento?' %}
            </tr>
            <tr>
              <td colspan="12" class="hiddenRow">
                    <div class="accordian-body collapse" id="{{proc.id}}">
                  <table class="table listra">
                    <th class="title-table" scope="col" style="padding: 15px">EXAMES INDICADOS</th>
                    <th class="title-table" scope="col" style="padding: 15px; padding-right: 70px;">LOCAIS INDICADOS</th>
                    <tr>
                      <td class="contant-table">
                        <div class="item-table">
                          <ul >Nome:</ul>
                          <p>{{proc.title}}</p>
                        </div>
                        <div class="item-table">
                          <ul>Descrição</ul>
                          <p>{{proc.description}}</p>
                        </div>
                      </td>
                      <td>
                        <div class="sugestao">
                          
                        {% for procreco in proc.procedurereco_set.all%}
                        <ul>{{procreco.recommendation.name}}</ul>
                        {% endfor %}
                        </div>
                      </td>
                    </tr>
                  </table>
                </div>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    
        <div class="container_pagination">      
            <nav aria-label="Page-navigation">
                <ul class="pagination">
                    {% if proc.has_previous %}
                        <li class="page-item ">
                            <a class="page-link" href="?page={{proc.previous_page_number}}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
                        </li>
                    {% endif %}
                    <li class="page-item"><a class="page-link" href="#">Página {{proc.number}} de {{proc.paginator.num_pages}}</a></li>
                    {% if proc.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{proc.next_page_number}}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span></a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endblock body %}